[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint.per-file-ignores]
"engine/services/generator.py" = ["F401", "F841"]

[tool.black]
line-length = 100
target-version = ["py311"]
extend-exclude = "^/engine/"

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "engine.services.generator"
ignore_errors = true
